import PageShell from "@/components/PageShell";
import { P, H2 } from "@/components/Prose";
import { buildMetadata } from "@/lib/metadata";
import { SITE_NAME, CONTACT_EMAIL } from "@/lib/site";

export const metadata = buildMetadata({
  title: "Terms of Use",
  description: `The terms governing your use of ${SITE_NAME}, including acceptable use and limitations.`,
  path: "/terms",
});

export default function TermsPage() {
  return (
    <PageShell
      title="Terms of Use"
      intro="By using this site, you agree to these terms. Please read them carefully."
      crumbs={[{ label: "Home", href: "/" }, { label: "Terms" }]}
    >
      <H2>Informational purpose only</H2>
      <P>
        {SITE_NAME} provides calculators and educational content for general
        informational and educational purposes only. Nothing on this site is
        intended as medical, nutritional, or professional advice, and it should
        not be treated as a substitute for guidance from a qualified
        professional.
      </P>

      <H2>Acceptable use</H2>
      <P>
        You agree to use this site lawfully and reasonably. You may not attempt
        to disrupt or interfere with the site&apos;s operation, misuse its
        content, scrape it in ways that burden our infrastructure, or use it for
        any unlawful purpose. The content here is provided for your personal,
        non-commercial use unless we say otherwise.
      </P>

      <H2>No guarantee of results</H2>
      <P>
        Fitness and nutrition outcomes depend on many individual factors. We make
        no promises or guarantees about specific results from using our
        calculators or following our content. The figures our tools produce are
        estimates generated by standard formulas, and individual needs vary.
      </P>

      <H2>Your responsibility</H2>
      <P>
        You are responsible for your own health, nutrition, and training
        decisions. Before acting on any information from this site, consider your
        personal circumstances and consult an appropriate professional. By using
        the site, you accept that you do so at your own discretion and risk.
      </P>

      <H2>Accuracy and availability</H2>
      <P>
        We work to keep the site accurate and available, but we do not warrant
        that it will always be error-free, current, or uninterrupted. We may
        update, change, or remove content and features at any time without
        notice.
      </P>

      <H2>Limitation of liability</H2>
      <P>
        To the fullest extent permitted by law, {SITE_NAME} and its operators are
        not liable for any losses or damages arising from your use of, or
        reliance on, the site or its content.
      </P>

      <H2>Third-party links</H2>
      <P>
        The site may link to third-party websites or services. We are not
        responsible for the content, policies, or practices of those external
        sites.
      </P>

      <H2>Changes to these terms</H2>
      <P>
        We may revise these terms periodically. Continued use of the site after
        changes are posted means you accept the updated terms.
      </P>

      <H2>Contact</H2>
      <P>
        Questions about these terms? Email{" "}
        <a
          href={`mailto:${CONTACT_EMAIL}`}
          className="font-semibold text-ink underline decoration-lime-deep underline-offset-2"
        >
          {CONTACT_EMAIL}
        </a>
        .
      </P>
    </PageShell>
  );
}
